# Generated by Django 5.2.8 on 2025-11-28 16:40

import offer_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='owner',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=offer_app.models.user_directory_path),
        ),
    ]
