# Generated by Django 5.2.8 on 2025-12-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_ordercountinprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed'), ('canceled', 'canceled')], default='in_progress'),
        ),
    ]
