# Generated by Django 5.2.8 on 2025-11-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_alter_profile_description_alter_profile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
